### ISSUE TITLE
[VITA-BOOTANIM] GIF loops forever

### ISSUE THREAD

**Issue by EntireCircus** [SKGleba/VitaTools#6] opened 2021-07-11 16:16 UTC
As the title suggests, gif loops indefinitely, presumably even after bootup is complete (short pressing power button turns screen off but turning it back on still just shows the gif)

**Comment by SKGleba** [comment] 2021-07-11 17:16
duplicate of https://github.com/SKGleba/VitaTools/issues/3

**Closed by SKGleba** 2021-07-11 17:16 UTC

**Comment by SKGleba** [comment] 2021-07-11 20:55
try the latest version (requires recompiling the animation or changing priority in boot animation settings)
